var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(chat)/chat/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~ksb~d._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0najft5.js")
R.c("server/chunks/ssr/[root-of-the-server]__12w~j-2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11ry5og._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(chat)_layout_tsx_0.lu.no._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(chat)_chat_[id]_page_actions_02dzzi1.js")
R.m(96255)
module.exports=R.m(96255).exports
